### ISSUE TITLE
Add py.typed?

### ISSUE THREAD

**Issue by sminnee** [sbdchd/django-types#129]
Pylance in VSCode doesn't appear to use this package in favour of its built-in typeshed types.

Reading through https://github.com/microsoft/pylance-release/issues/1197 it sounds like any modules marked as py.typed will be used in favour of typeshed types.

In that context, would it make senes to mark this module as py.typed?

**Comment by sbdchd** [comment]
Ah interesting, from https://peps.python.org/pep-0561/#stub-only-packages I thought the name -stubs would be enough, but adding a py.typed file couldn't hurt I guess

still feels like a bug on the pylance side of things

**Comment by rafsaf** [comment]
I would be interested in merging this: https://github.com/sbdchd/django-types/pull/135

Nice spot @sminnee! I can confirm it indeed works (adding py.typed file), had no idea why pylance didn't prefer those stubs (which are much better than bundled ones used to be) over bundled... and I just needed every time to delete bundled django stubs which is a little annoying

Funny thing is, since yesterday MS pylance now use **this** package for stubs so it's not a problem anymore (unless there are new releases etc) https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022940-26-september-2022-release
