### ISSUE TITLE
No parameter named "<attr>" for some django columns even with typing correctly set

### ISSUE THREAD

**Issue by bellini666** [sbdchd/django-types#29]
Hi @sbdchd . First of all, thanks for all your work here to allow `django-stubs` to be used without mypy

I'm having some issues when passing some attributes to some columns (e.g. `decimal_places` on `DecimalField`). AFAIK they are properly mapped, but pyright keeps giving me errors regarding it.

I first opened the issue on pyright here (https://github.com/microsoft/pyright/issues/2077) because I thought it was their fault, but it might not be.

Any ideas on how/why this is happening? You can check my example code here (https://github.com/microsoft/pyright/issues/2077#issuecomment-877857826) and run it with pyright and you will get the exact same issues that I got.

**Comment by bellini666** [comment]
The maintainer there pointed that it might have something to do with `__new__`. I'm old to python but new to typing, so I'm not really sure what is going on yet.

**Comment by sbdchd** [comment]
Thanks for the report!

The `__new__` / `__init__` overloads are really hacks to get the types to behave with both pyright and mypy

Basically we want to type these fields as generics so we can overload the `__get__` and `__set__` properly, i.e., a nullable integer results in a `int | None`.

Mypy tends to be more flexible with "self overloads", aka overloading `__init__` with a type on the `self` param so we can set the generic param based on the arguments of the `__init__`, but to get `pyright` to be happy we sometimes have to opt to overload `__new__`.


semi related:

https://github.com/microsoft/pyright/issues/1550
https://github.com/microsoft/pyright/issues/1211

Anyways, should be fixed in 0.6.0, let me know if you run into any other issues!

**Comment by bellini666** [comment]
Hi @sbdchd ,

Thank you! I'll try the new upate and come back if I find any other issue.
